spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

logging:
  level:
    org:
      springframework: info
    com:
      twice_thinker:
        api_gateway: debug

server:
  port: ${SERVER_PORT}
#
##Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

#spring.jpa.defer-datasource-initialization=true
