spring:
  application:
    name: "service-registry"

logging:
  level:
    org:
      springframework: info

server:
  port: ${SERVER_PORT}

eureka:
  instance:
    hostname: service-registry
  client:
    registerWithEureka: false
    fetchRegistry: false
